name: Build Tweak
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Tweak
        uses: Randomblock1/theos-action@v1
        with:
          theos-dir: 'theos'
          theos-src: 'https://github.com/theos/theos'
          theos-sdks: 'https://github.com/theos/sdks'
          theos-sdks-branch: 'master'
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: instpls.deb
          path: ./*.deb
